# Change these first
owner: MBTechLabs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Kadjoe
    url: https://kadjoe.com
  - name: Sentrallab
    url: https://sentrallabgenetik.co.id
  - name: Soutbarn
    url: https://southbarn.id
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime Status**"
  introMessage: Melon Branding's status page, with real-time response times, uptime and status history.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
