# Change these first
owner: MBTechLabs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Kadjoe
    url: https://kadjoe.com
  - name: Sentrallab
    url: https://sentrallabgenetik.co.id
  - name: Soutbarn
    url: https://southbarn.id
  - name: Pipaslg
    url: https://pipaslg.com
  - name: Trovee Studio
    url: https://troveestudio.com
  - name: Ballooney
    url: https://ballooney.co.id
  - name: Jaroemsadha
    url: https://jaroemsadha.com
  - name: Decor House Indonesia
    url: https://decorhouseindonesia.com
  - name: Somnum Chalets
    url: https://somnumchalets.com
  - name: Sugar Filtrations Screen
    url: https://sugarfiltrationscreens.com
  - name: Souma Movement
    url: https://soumamovement.com
  - name: Carne Ristorante
    url: https://carneristorante.com
  - name: Andsonsarana
    url: https://andsonsarana.com
  - name: Monelo
    url: https://monelo.id
  - name: Melon
    url: https://melonbranding.com
  - name: Homecarefs
    url: https://homecarefs.com.au
  - name: Pilates
    url: https://pilatescapital.com
  - name: Inkprint
    url: https://inkprint.id
  - name: Karunia Utama
    url: https://karuniautama.id
  - name: Koalisi tubindo
    url: https://koalisitubindo.com
  - name: Lavronque
    url: https://lavronque.com
  - name: Heir Care Studio
    url: https://heircarestudio.com
  - name: Buana Cahaya Abadi
    url: https://buanacahayaabadi.com
  - name: Vitablitz
    url: https://vitablitzherbal.com
  - name: Direct Station
    url: https://directstation.co.id
  - name: Tiga Sumber Audio
    url: https://tigasumberaudio.com
  - name: Elora
    url: https://elora.co.id
  - name: Tiang Living
    url: https://tiangliving.com
  - name: Hamparan Harapan Hayati
    url: https://hamparanharapanhayati.com
  - name: Silikal
    url: https://silikal.com.au
  - name: HRD Venture Trade
    url: https://hrd-venture-trade.com
  - name: Qteknos
    url: https://www.qteknos.com
  - name: Prada Setia
    url: https://pradasetia.com
  - name: RMSP
    url: https://rmsp.co.id
  - name: Marvelo Leather
    url: https://marveloleather.com
  - name: Caferoove
    url: https://caferoovee.com
  - name: RDS Indo
    url: https://rds.co.id
  - name: Mentari Freight
    url: https://mentarifreight.com
  - name: RDS Singapore
    url: https://rds.sg
  - name: RDS Vietnam
    url: https://rdsvietnam.vn
  - name: Alpha MT
    url: https://alpha-mt.com
  - name: Silverplas
    url: https://silverplas.co.id
  - name: Ispak
    url: https://ispak.co.id
  - name: Rigo Metal Furniture
    url: https://rigometalfurniture.com
  - name: Wisakademi
    url: https://www.wisakademi.com
  - name: Giga Solusi
    url: https://gigasolusi.co.id
  - name: Putra Bhakti Court
    url: http://www.putrabhakticourt.com
  - name: Risman Hotel
    url: https://therismanhotel.com
  - name: Prodia OHI
    url: https://prodiaohi.co.id
  - name: Tjajolaw
    url: https://tjajolaw.id
  - name: Blue Power Technology
    url: https://www.bluepowertechnology.com
  - name: Ikarao
    url: https://ikarao.id
  - name: CV Anugerah Lestari
    url: https://anugerahlestari.co.id
  - name: Hamparan Stone
    url: https://hamparanstone.com
  - name: Stellarfm
    url: http://stellarfm.com.au
  - name: GKI Kelapa Cengkir
    url: https://gkikelapacengkir.org
  - name: Majalah Sunday
    url: https://majalahsunday.com
  - name: Montana Design
    url: http://montanadesign.co.id
  - name: Jawara System
    url: https://www.jawarasystems.io
  - name: Bestra
    url: https://www.bestra.co.id
  - name: BW Indonesia
    url: https://bw-indonesia.com
  - name: KPSG
    url: https://kpsg.com
  - name: Romeesa Design
    url: https://romeesadesign.co.id
  - name: Jayananta Anugerah Sejati
    url: https://jayanantaanugerahsejati.com
  - name: The Ahad
    url: https://www.the-ahad.com
  - name: ARSI
    url: https://arsi.ai
  - name: EGEROO
    url: https://egeroo.ai
  - name: PayPrime
    url: https://payprime.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime Status**"
  introMessage: Melon Branding's status page, with real-time response times, uptime and status history.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
